apiVersion: batch/v1
kind: Job
metadata:
  name: dnscrypt-init
spec:
  template:
    metadata:
      name: dnscrypt-init
    spec:
      containers:
      - name: dnscrypt-init
        image: zquestz/dnscrypt-server:latest
        imagePullPolicy: Always
        command: ["/entrypoint.sh", "init", "-A", "-M", "0.0.0.0:9100", "-N", "visionati.com", "-E", "35.206.115.121:5443"]
        volumeMounts:
          - name: dnscrypt-keys
            mountPath: /opt/encrypted-dns/etc/keys
      restartPolicy: Never
      volumes:
        - name: dnscrypt-keys
          gcePersistentDisk:
            pdName: dnscrypt-keys
            fsType: ext4
