apiVersion: v1
kind: Service
metadata:
  name: dnscrypt-tcp
  namespace: default
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  ports:
    - protocol: TCP
      port: 5443
      targetPort: 5443
  selector:
    service: dnscrypt
  type: LoadBalancer
  loadBalancerIP: 35.206.115.121
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: dnscrypt-udp
  namespace: default
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  ports:
    - protocol: UDP
      port: 5443
      targetPort: 5443
  selector:
    service: dnscrypt
  type: LoadBalancer
  loadBalancerIP: 35.206.115.121
  externalTrafficPolicy: Local
